### ISSUE TITLE
Adding button to clean ram cache

### ISSUE THREAD

**Issue by StefanescuCristian** [dorimanx/initramfs3#3]
Well, since I got "removed" from XDA making this request, I will ask it here.

Could you include a button in Stweaks that mimics "clean ram cache every hour" from cron and activates cleaning after it is pressed?

Thank you.

**Comment by dorimanx** [comment]
yes i can, removed from XDA? WFT? why?
that is not right.

**Comment by StefanescuCristian** [comment]
Apparently I posted in the wrong thread. It's OK, don't worry.
Thanks.
