### ISSUE TITLE
Stweaks settings won't remain

### ISSUE THREAD

**Issue by voku** [dorimanx/initramfs3#4]
Situation:
tested for 3 times with 2 kernel reinstall (with kernel wipe script and wiping cache/dalvik)

Problem: 
Stweaks settings won't remain for "I/O", "Memory", "Other" & "Tweaks" tabs and also touch freq and 2nd core freq
they will reset after reboot to their default selected profile values

-> reported by "KINGTATu" at xda [http://forum.xda-developers.com/showthread.php?p=38095132&posted=1#post38095132]

**Comment by Shahrokh-KING** [comment]
Debug & Logcat:
http://fs2.filegir.com/shahrokh.king/Debug-Logcat.zip

**Comment by dorimanx** [comment]
USER BUG! ERROR!

Clean /data/.siyah/

reboot, set your settings, wait 1 min. reboot.

# 

~ # /res/uci.sh restore
/res/uci.sh restore
applying: /res/uci_for_loop.sh generic_cortex /tmp/boot_boost 1500000
1500000
applying: /res/uci_for_loop.sh generic_cortex /tmp/booster_sleep_max 90
90
applying: /res/uci_for_loop.sh genericfreq_normal /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 1200000
1200000
applying: /res/uci_for_loop.sh genericfreq_oc /tmp/scaling_max_freq_oc 1500000
1500000
applying: /res/uci_for_loop.sh genericfreq /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 100000
100000
applying: /res/uci_for_loop.sh genericfreq /sys/devices/virtual/sec/sec_touchscreen/tsp_touch_freq 300000
300000
applying: /res/uci_for_loop.sh genericfreq /sys/module/stand_hotplug/parameters/freq_min 600000
600000
applying: /res/uci_for_loop.sh generickmem smooth_level 0 int 0
0
applying: /res/uci_for_loop.sh generic /sys/module/stand_hotplug/parameters/load_h0 20
20
applying: /res/uci_for_loop.sh generic /sys/module/stand_hotplug/parameters/load_l1 20
20
applying: /res/uci_for_loop.sh generic /sys/module/stand_hotplug/parameters/min_rq 2
2
applying: /res/uci_for_loop.sh generic /sys/module/stand_hotplug/parameters/load_rq 20
20
applying: /res/uci_for_loop.sh generic /sys/module/stand_hotplug/parameters/rate 100
100
applying: /res/uci_for_loop.sh schedfeat GENTLE_FAIR_SLEEPERS off
off
applying: /res/uci_for_loop.sh schedfeat ARCH_POWER on
on
applying: /res/uci_for_loop.sh generic /sys/module/cpuidle_exynos4/parameters/enable_mask 3
3
applying: /res/uci_for_loop.sh generic_cortex /tmp/enable_mask_sleep 3
3
applying: /res/uci_for_loop.sh generic /sys/devices/system/cpu/cpufreq/busfreq_up_threshold 80
80
applying: /res/uci_for_loop.sh genericfreq /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_suspend_freq 600000
600000
applying: /res/uci_for_loop.sh genericfreq /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_suspend_freq 100000
100000
applying: /res/uci_for_loop.sh genericfreq /tmp/standby_freq 100000
100000
applying: /res/uci_for_loop.sh generic_cortex /tmp/wakeup_delay 0
0
applying: /res/uci_for_loop.sh generic_cortex /tmp/wakeup_boost 5
5
applying: /res/uci_for_loop.sh generic_cortex /tmp/cpu_voltage_switch off
off
applying: /res/uci_for_loop.sh cpu-voltage 1 1450
1450
applying: /res/uci_for_loop.sh cpu-voltage 2 1400
1400
applying: /res/uci_for_loop.sh cpu-voltage 3 1375
1375
applying: /res/uci_for_loop.sh cpu-voltage 4 1350
1350
applying: /res/uci_for_loop.sh cpu-voltage 5 1275
1275
applying: /res/uci_for_loop.sh cpu-voltage 6 1250
1250
applying: /res/uci_for_loop.sh cpu-voltage 7 1225
1225
applying: /res/uci_for_loop.sh cpu-voltage 8 1200
1200
applying: /res/uci_for_loop.sh cpu-voltage 9 1175
1175
applying: /res/uci_for_loop.sh cpu-voltage 10 1150
1150
applying: /res/uci_for_loop.sh cpu-voltage 11 1125
1125
applying: /res/uci_for_loop.sh cpu-voltage 12 1100
1100
applying: /res/uci_for_loop.sh cpu-voltage 13 1075
1075
applying: /res/uci_for_loop.sh cpu-voltage 14 1050
1050
applying: /res/uci_for_loop.sh cpu-voltage 15 1050
1050
applying: /res/uci_for_loop.sh cpu-voltage 16 1025
1025
applying: /res/uci_for_loop.sh cpu-voltage 17 1025
1025
applying: /res/uci_for_loop.sh cpu-voltage 18 1000
1000
applying: /res/uci_for_loop.sh cpu-voltage 19 975
975
applying: /res/uci_for_loop.sh cpu-voltage 20 975
975
applying: /res/uci_for_loop.sh cpu-voltage 21 975
975
applying: /res/uci_for_loop.sh cpu-voltage 22 975
975
applying: /res/uci_for_loop.sh cpu-voltage 23 975
975
applying: /res/uci_for_loop.sh cpu-voltage 24 950
950
applying: /res/uci_for_loop.sh cpu-voltage 25 950
950
applying: /res/uci_for_loop.sh cpu-voltage 26 925
925
applying: /res/uci_for_loop.sh cpu-voltage 27 925
925
applying: /res/uci_for_loop.sh generic /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor nightmare
nightmare
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_lock 0
0
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_threshold 60
60
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_rate 50000
50000
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_down_factor 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_step 30
30
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_differential 1
1
applying: /res/uci_for_loop.sh genericfreq /tmp/freq_for_responsiveness 400000
400000
applying: /res/uci_for_loop.sh generic_cortex /tmp/inc_cpu_load 50
50
applying: /res/uci_for_loop.sh generic_cortex /tmp/dec_cpu_load 40
40
applying: /res/uci_for_loop.sh generic_cortex /tmp/cpu_up_rate 10
10
applying: /res/uci_for_loop.sh generic_cortex /tmp/cpu_down_rate 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_threshold 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_up_factor 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_latency_one_core 60000
60000
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_latency_two_cores 50000
50000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_for_calc_incr 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_for_calc_decr 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_cpu1on 900000
900000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_cpu1off 700000
700000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_step_dec 10
10
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_up_brake 35
35
applying: /res/uci_for_loop.sh generic_cortex /tmp/inc_cpu_load_at_min_freq 40
40
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_h0 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_h1 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_l1 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_rq 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_rq 2
2
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_threshold_at_min_freq 40
40
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_sampling_rate 40000
40000
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_sample_time 40000
40000
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_sample_time 20000
20000
applying: /res/uci_for_loop.sh generic_cortex /tmp/pump_up_step 2
2
applying: /res/uci_for_loop.sh generic_cortex /tmp/pump_down_step 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/screen_off_min_step 11
11
applying: /res/uci_for_loop.sh genericfreq /tmp/hispeed_freq 1200000
1200000
applying: /res/uci_for_loop.sh genericfreq /tmp/hotplug_freq_1_1 500000
500000
applying: /res/uci_for_loop.sh genericfreq /tmp/hotplug_freq_2_0 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_rq_1_1 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_rq_2_0 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/deep_sleep ondemand
ondemand
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_lock_sleep 0
0
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_threshold_sleep 75
75
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_rate_sleep 70000
70000
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_down_factor_sleep 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_step_sleep 30
30
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_differential_sleep 1
1
applying: /res/uci_for_loop.sh genericfreq /tmp/freq_for_responsiveness_sleep 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/inc_cpu_load_sleep 80
80
applying: /res/uci_for_loop.sh generic_cortex /tmp/dec_cpu_load_sleep 70
70
applying: /res/uci_for_loop.sh generic_cortex /tmp/cpu_up_rate_sleep 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/cpu_down_rate_sleep 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_threshold_sleep 30
30
applying: /res/uci_for_loop.sh generic_cortex /tmp/sampling_up_factor_sleep 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_latency_one_core_sleep 70000
70000
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_latency_two_cores_sleep 70000
70000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_for_calc_incr_sleep 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_for_calc_decr_sleep 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_cpu1on_sleep 600000
600000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_cpu1off_sleep 500000
500000
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_step_dec_sleep 10
10
applying: /res/uci_for_loop.sh generic_cortex /tmp/freq_up_brake_sleep 35
35
applying: /res/uci_for_loop.sh generic_cortex /tmp/inc_cpu_load_at_min_freq_sleep 60
60
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_h0_scroff 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_h1_scroff 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_l1_scroff 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_load_rq_sleep 20
20
applying: /res/uci_for_loop.sh generic_cortex /tmp/trans_rq_sleep 2
2
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_threshold_at_min_freq_sleep 70
70
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_sampling_rate_sleep 15000
15000
applying: /res/uci_for_loop.sh generic_cortex /tmp/up_sample_time_sleep 60000
60000
applying: /res/uci_for_loop.sh generic_cortex /tmp/down_sample_time_sleep 10000
10000
applying: /res/uci_for_loop.sh generic_cortex /tmp/pump_up_step_sleep 1
1
applying: /res/uci_for_loop.sh generic_cortex /tmp/pump_down_step_sleep 3
3
applying: /res/uci_for_loop.sh generic_cortex /tmp/screen_off_min_step_sleep

applying: /res/uci_for_loop.sh genericfreq /tmp/hispeed_freq_sleep 400000
400000
applying: /res/uci_for_loop.sh genericfreq /tmp/hotplug_freq_1_1_sleep 500000
500000
applying: /res/uci_for_loop.sh genericfreq /tmp/hotplug_freq_2_0_sleep 200000
200000
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_rq_1_1_sleep 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/hotplug_rq_2_0_sleep 100
100
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_read_ahead_kb 2048
2048
applying: /res/uci_for_loop.sh generic /sys/block/mmcblk0/queue/scheduler zen
zen
applying: /res/uci_for_loop.sh generic /sys/block/mmcblk0/queue/sleep_scheduler noop
noop
applying: /res/uci_for_loop.sh oom_config_screen_on medium
medium
applying: /res/uci_for_loop.sh oom_config_screen_off medium
medium
applying: /res/uci_for_loop.sh generic /proc/sys/vm/dirty_background_ratio 30
30
applying: /res/uci_for_loop.sh generic /proc/sys/vm/dirty_ratio 40
40
applying: /res/uci_for_loop.sh zramtweaks 4
4
applying: /res/uci_for_loop.sh generic /proc/sys/vm/swappiness 0
0
applying: /res/uci_for_loop.sh generic_ksm /tmp/cortexbrain_ksm_control off
off
applying: /res/uci_for_loop.sh generic01 /sys/module/mali/parameters/mali_use_vpll on
on
applying: /res/uci_for_loop.sh generic /sys/module/mali/parameters/mali_gpu_utilization_timeout 150
150
applying: /res/uci_for_loop.sh gpu-freq 1 108
108
applying: /res/uci_for_loop.sh gpu-freq 2 160
160
applying: /res/uci_for_loop.sh gpu-freq 3 200
200
applying: /res/uci_for_loop.sh gpu-freq 4 330
330
applying: /res/uci_for_loop.sh gpu-freq 5 400
400
applying: /res/uci_for_loop.sh gpu-voltage 1 900
900
applying: /res/uci_for_loop.sh gpu-voltage 2 950
950
applying: /res/uci_for_loop.sh gpu-voltage 3 1000
1000
applying: /res/uci_for_loop.sh gpu-voltage 4 1100
1100
applying: /res/uci_for_loop.sh gpu-voltage 5 1200
1200
applying: /res/uci_for_loop.sh gpu-thresh 1UP 30
30
applying: /res/uci_for_loop.sh gpu-thresh 2DOWN 20
20
applying: /res/uci_for_loop.sh gpu-thresh 2UP 40
40
applying: /res/uci_for_loop.sh gpu-thresh 3DOWN 30
30
applying: /res/uci_for_loop.sh gpu-thresh 3UP 55
55
applying: /res/uci_for_loop.sh gpu-thresh 4DOWN 45
45
applying: /res/uci_for_loop.sh gpu-thresh 4UP 80
80
applying: /res/uci_for_loop.sh gpu-thresh 5DOWN 70
70
applying: /res/uci_for_loop.sh generic /sys/bus/i2c/devices/3-004a/mov_hysti 1
1
applying: /res/uci_for_loop.sh generic /sys/class/misc/brightness_curve/min_bl 30
30
applying: /res/uci_for_loop.sh generic /sys/class/misc/brightness_curve/min_gamma 1
1
applying: /res/uci_for_loop.sh generic /sys/class/misc/brightness_curve/max_gamma 23
23
applying: /res/uci_for_loop.sh generic01 /sys/class/lcd/panel/power_reduce on
on
applying: /res/uci_for_loop.sh generic /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cb 127
127
applying: /res/uci_for_loop.sh generic /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cr 127
127
applying: /res/uci_for_loop.sh generic01 /tmp/mdniemod off
off
applying: /res/uci_for_loop.sh generic /sys/class/lcd/panel/user_gamma_adjust 5
5
applying: /res/uci_for_loop.sh generickmem fbearlysuspend_delay 0 int 50
50
applying: /res/uci_for_loop.sh generic /sys/vibrator/pwm_val 75
75
applying: /res/uci_for_loop.sh generic01 /sys/devices/virtual/sec/sec_touchscreen/tsp_slide2wake on
on
applying: /res/uci_for_loop.sh generic01 /sys/module/gpio_keys/parameters/mdnie_shortcut_enabled off
off
applying: /res/uci_for_loop.sh negative_tweak 1
1
applying: /res/uci_for_loop.sh generic_gestures /tmp/gesture_tweak on
on
applying: /res/uci_for_loop.sh touch_screen_tweak 1 50
50
applying: /res/uci_for_loop.sh touch_screen_tweak 2 40
40
applying: /res/uci_for_loop.sh touch_screen_tweak 3 12
12
applying: /res/uci_for_loop.sh touch_screen_tweak 4 53
53
applying: /res/uci_for_loop.sh touch_screen_tweak 5 38
38
applying: /res/uci_for_loop.sh touch_screen_tweak 6 47
47
applying: /res/uci_for_loop.sh generic_cortex /tmp/jb_sound_fix on
on
applying: /res/uci_for_loop.sh soundgasm_hp 2
2
applying: /res/uci_for_loop.sh sound_volume 1 8
8
applying: /res/uci_for_loop.sh sound_volume 4 2
2
applying: /res/uci_for_loop.sh sound_volume 2 0
0
applying: /res/uci_for_loop.sh sound_volume 3 4
4
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/notification_enabled on
on
applying: /res/uci_for_loop.sh bln_switch 0
0
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/notification_timeout 600000
600000
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/led_timeout_ms 3000
3000
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/blnww on
on
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/led_fadeout on
on
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/led_on_touch off
off
applying: /res/uci_for_loop.sh generic /sys/devices/virtual/sec/sec_touchkey/touchkey_brightness 3000
3000
applying: /res/uci_for_loop.sh generic /sys/class/misc/notification/dyn_brightness on
on
applying: /res/uci_for_loop.sh crontab on
nohup: appending output to nohup.out
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cron_drop_cache off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/ad_block_update on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cron_db_optimizing on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cron_clear_app_cache on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cron_fix_permissions off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/cron_zipalign on
on
applying: /res/uci_for_loop.sh supplicant_scan_interval 120
120
applying: /res/uci_for_loop.sh gpsregion No_GPS_Zone_changes
No_GPS_Zone_changes
applying: /res/uci_for_loop.sh usb-mode default
default
applying: /res/uci_for_loop.sh generic_cortex /tmp/auto_mount_sd on
on
applying: /res/uci_for_loop.sh chargecurrent 1 700
700
applying: /res/uci_for_loop.sh chargecurrent 2 700
700
applying: /res/uci_for_loop.sh chargecurrent 3 500
500
applying: /res/uci_for_loop.sh generic01 /sys/module/wakelock/parameters/default_stats off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/init_d off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/logger off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/install_root on
on
applying: /res/uci_for_loop.sh cortexbrain_background_process 1
1
applying: /res/uci_for_loop.sh android_logger auto
auto
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_auto_tweak_wifi off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_auto_tweak_wifi_sleep_delay 30
30
applying: /res/uci_for_loop.sh generic_cortex /tmp/wifi_pwr off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_firewall on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_tcp on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_ipv6 off
off
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_cpu on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_memory on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_battery on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_system on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_kernel_tweaks on
on
applying: /res/uci_for_loop.sh generic_cortex /tmp/cortexbrain_io on
on
applying: /res/uci_for_loop.sh no-boot-logo off
off
applying: /res/uci_for_loop.sh defaultrom
~ #

**Comment by voku** [comment]
But I readed about this problem, in different forums/threads ... so maybe we  can add a workaround? e.g. saving a file (flag) to the filesystem, when a kernel with a different build-time is booting for the first time the backup the config, cleaning /data/.siyah/ & restore the config?!
