### ISSUE TITLE
Boot boost not working as intended

### ISSUE THREAD

**Issue by StefanescuCristian** [dorimanx/initramfs3#5]
Maybe it's chip-dependant, but it might affect all phones

How it should work:
-setting min_freq = max_freq =boot_freq for a T time
-boot using the boot_freq as frequency
-all people are happy

How it actually works (and why):
-setting min_freq = max_freq =boot_freq for a T time
-boot using the boot_freq as frequency
-the CPU will scale from boot_freq to 800MHz due to heat/prolonged load making boot time worse or in the best case not improved at all

Maybe a fix:
-set min_freq to somethilg like max_freq - 2/300MHz
-governor will scale between these freqs and hopefully the cpu will not become as hot as it will with a fixed freq

**Comment by dorimanx** [comment]
DONE.
https://github.com/dorimanx/initramfs3/commit/5ca5ef1610dde20f137d72be214c28048afb23b3

Thanks.
